#!/usr/bin/env bash
# list the type of record and ip

on () {
  echo "$sub $inf" | awk '{ print "The subdomain " $1 " is a " $5 " record and points to " $6 }'
}

if [[ $# -lt 2 ]];
then
  dom=("www" "lb-01" "web-01" "web-02")
  for sub in "${dom[@]}"; do
    inf=$(dig "$sub.$1" | grep -A1 ";; ANSWER" | tail -n 1)
    on
  done
else
  sub=$2
  inf=$( dig "$2.$1" | grep -A1 ";; ANSWER" | tail -n 1 )
  on
fi
