#!/usr/bin/env bash
# list the type of record and ip

info () {
    solv=$(dig "$2" | grep -A1 'solv SECTION:' | awk 'NR==2 {print $0}')
    echo "The subdomain $1 is a $(echo "$solv" | awk '{print $4}') record and points to $(echo "$solv" | awk '{print $5}')"
}

if [[ $# == 1 ]]; then
    subdomains=('www' 'lb-01' 'web-01' 'web-02')
    for i in "${subdomains[@]}"; do
	url="$i.$1"
	info "$i $url"
    done
else
    url="$2.$1"
    info "$2 $url"
fi
