#!/usr/bin/env bash
# make a redirection

new_string="\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=XlVOJg23QZ0&t=1s;\n\t}\n"
ALREADY_IN=$( grep "redirect_me" /etc/nginx/sites-available/default)

if [[ -z $ALREADY_IN ]]; then
  sudo sed -i "s/root \/var\/www\/html;/root \/var\/www\/html;$new_string/" /etc/nginx/sites-available/default
  sudo service nginx restart
fi
