#!/usr/bin/env bash
# make a redirection

new_string="\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=XlVOJg23QZ0&t=1s;\n\t}\n"
ALREADY_IN=$( grep "redirect_me" ./test.conf)

if [[ -z $ALREADY_IN ]]; then
sudo sed -i "s/root \/var\/www\/html;/root \/var\/www\/html;$new_string/" ./test.conf
fi
