#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html

new_string="\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=XlVOJg23QZ0&t=1s;\n\t}\n"
exist=$( grep "redirect_me" /etc/nginx/sites-available/default)
if [[ -z $exist ]]; then
  sudo sed -i "s/root \/var\/www\/html;/root \/var\/www\/html;$new_string/" /etc/nginx/sites-available/default
fi

new_string="\n\n\terror_page 404 \/page404.html;\n\tlocation = \/page404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}\n"
exist=$( grep "error_page" /etc/nginx/sites-available/default)

if [[ -z $exist ]]; then
  echo "Ceci n'est pas une page" | sudo tee /var/www/html/page404.html
  sudo sed -i "s/root \/var\/www\/html;/root \/var\/www\/html;$new_string/" /etc/nginx/sites-available/default
fi

new_header="\tadd_header X-Served-By $HOSTNAME;"
exist=$( grep "X-Served-By" /etc/nginx/sites-available/default )
if [[ -z $exist ]]; then
  sudo sed -i "s/root \/var\/www\/html;/root \/var\/www\/html;\n\n$new_header\n/" /etc/nginx/sites-available/default
fi

sudo service nginx restart
