#!/usr/bin/env bash
# Down load and configure haproxy

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install haproxy

echo '
frontend wilf.com
        bind wilf:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 2354-web-01 104.196.191.64
        server 2354-web-02 35.185.77.2
' >> /etc/haproxy/haproxy.cfg

sudo service haproxy reload
sudo service haproxy restart
