#!/usr/bin/env bash
# Install and configure ufw


sudo apt-get update
sudo apt-get -y install ufw

echo y | sudo ufw enable

sudo ufw default deny incoming
sudo ufw allow ssh
sudo ufw allow 443
sudo ufw allow 80
